"""Initial revision

Revision ID: 43b1a58434ca
Revises: 
Create Date: 2025-11-18 08:02:09.916461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43b1a58434ca'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('telegram_id')
    )
    op.create_table('blacklist',
    sa.Column('blacklist_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('time_start', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('time_finish', sa.DateTime(), nullable=False),
    sa.Column('time_update', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('canceled', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.telegram_id'], ),
    sa.PrimaryKeyConstraint('blacklist_id')
    )
    op.create_table('bookkorts',
    sa.Column('bookkort_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('time_create', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('time_start', sa.DateTime(), nullable=False),
    sa.Column('time_finish', sa.DateTime(), nullable=False),
    sa.Column('time_update', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('canceled', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.telegram_id'], ),
    sa.PrimaryKeyConstraint('bookkort_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bookkorts')
    op.drop_table('blacklist')
    op.drop_table('users')
    # ### end Alembic commands ###
